---
packages:
  from_repo:
    - 'adduser'
    - 'apt-transport-https'
    - 'auditd'
    - 'bash-completion'
    - 'ca-certificates'
    - 'cifs-utils'
    - 'conntrack' # for kubelet
    - 'containerd.io=1.5.11*'
    - 'curl'
    - 'docker-ce=5:20.10.8*'
    - 'docker-ce-cli=5:20.10.8*'
    - 'docker-ce-rootless-extras=5:20.10.8*'
    - 'ebtables'

    # for opensearch & logging roles
    - 'elasticsearch-oss=7.10.2*'
    - 'ethtool'
    - 'filebeat=7.12.1*'
    - 'firewalld'
    - 'fping'
    - 'gnupg2'
    - 'htop'
    - 'iftop'
    - 'iproute2' # for kubelet
    - 'jq'

    # for dpkg-scanpackages
    - 'libdpkg-perl'
    - 'libfontconfig1'
    - 'logrotate'
    - 'netcat'
    - 'net-tools'
    - 'nfs-common'

    # for nfs-common
    - 'libtirpc3'
    - 'openjdk-8-jre-headless'
    - 'openssl'
    - 'postgresql-13'
    - 'python3-psycopg2'
    - 'python3-selinux'
    - 'rabbitmq-server=3.8.9*'
    - 'smbclient'
    - 'samba-common'
    - 'software-properties-common'
    - 'sshpass'
    - 'sysstat'

    # for sysstat
    - 'libsensors5'
    - 'tar'
    - 'telnet'
    - 'tmux'
    - 'unzip'
    - 'vim'

    # to make remote-to-remote "synchronize" work in ansible
    - 'rsync'

    # for curl, issue #869
    - 'libcurl4'

    # for openjdk-8-jre-headless
    - 'libnss3'
    - 'libcups2'
    - 'libavahi-client3'
    - 'libavahi-common3'
    - 'libjpeg8'
    - 'libxtst6'
    - 'fontconfig-config'

    # for rabbit/erlang
    - 'libodbc1'

    # for air-gap repo installation
    - 'apache2'
    - 'apache2-bin'
    - 'apache2-utils'

    # for jq
    - 'libjq1'

    # for gnupg2
    - 'gnupg'
    - 'gpg'
    - 'gpg-agent'
    - 'samba-libs'
    - 'libsmbclient'

    # postgres related packages
    # if version is not specified, it's not related to postgres version and the latest is used
    - 'pgdg-keyring'
    - 'postgresql-13-pgaudit=1.5.0*'
    - 'postgresql-10-repmgr=5.2.1*'
    - 'postgresql-13-repmgr=5.2.1*'
    - 'postgresql-client-13'
    - 'postgresql-client-common'
    - 'postgresql-common'
    - 'repmgr-common=5.2.1*'

    # for firewalld
    - 'ipset'
    - 'python3-decorator'
    - 'python3-slip'
    - 'python3-slip-dbus'

    # for ansible module postgresql_query in role postgres-exporter
    - 'libpq5'
    - 'python3-jmespath'

    # for Ansible (certificate modules)
    - 'python3-cryptography'

    # for python3-cryptography
    - 'python3-cffi-backend'

  from_url:
    # Switched from APT repo because there was only one (the latest) version available (issue #2262)
    'https://packages.elastic.co/curator/5/debian9/pool/main/e/elasticsearch-curator/elasticsearch-curator_5.8.3_amd64.deb':
      sha256: 575a41184899678d9769a8ea120134ec329c41967c94586c1aa6439aa68d4829
    # Grafana package is not downloaded from repository since it was not reliable (issue #2449)
    'https://dl.grafana.com/oss/release/grafana_8.3.2_amd64.deb':
      sha256: 3f5ecf5726223314aa3147a24c732cc9ccede86b7d703d4835a6fc69d0fffff8
    # Switched to an alternate repository as K8s legacy repositories have been shut down
    'https://github.com/hitachienergy/alternative-repo/raw/main/2.0.x/x86_64/debian/packages/cri-tools_1.25.0-00_amd64.deb':
      sha256: 189468b949c777e07ca098365cbde0bcbe0c1fdbf8c406501f64bdbb447ae6f8
    'https://github.com/hitachienergy/alternative-repo/raw/main/2.0.x/x86_64/debian/packages/kubeadm_1.22.4-00_amd64.deb':
      sha256: 27ecaa5eba0ee0f4b9adb9460fdb571b414ad85f0ec1d6060009ea6fdeb3447d
    'https://github.com/hitachienergy/alternative-repo/raw/main/2.0.x/x86_64/debian/packages/kubectl_1.22.4-00_amd64.deb':
      sha256: 637b120b480b3ede53b93a140bc9d40df648e0ae1415da4a4d2584e1989fee92
    'https://github.com/hitachienergy/alternative-repo/raw/main/2.0.x/x86_64/debian/packages/kubelet_1.22.4-00_amd64.deb':
      sha256: 947ff062f2ba903fdd0ef77749219e8b27ca9c56821f503ae58a18a253fef5e1
    'https://github.com/hitachienergy/alternative-repo/raw/main/2.0.x/x86_64/debian/packages/kubernetes-cni_0.8.7-00_amd64.deb':
      sha256: ca2303ea0eecadf379c65bad855f9ad7c95c16502c0e7b3d50edcb53403c500f
    # Switched to an alternate repository as the following packages have been removed from erlang-solutions repository
    'https://github.com/hitachienergy/alternative-repo/raw/240393a45307781721021e597966da2a8291432f/2.0.x/x86_64/debian/packages/erlang-asn1_1%253a23.1.5-1_amd64.deb':
      sha256: bce3b3db06d4f3ae3487ea539fea39d77f11cefe510ac6642a718acee725989a
    'https://github.com/hitachienergy/alternative-repo/raw/240393a45307781721021e597966da2a8291432f/2.0.x/x86_64/debian/packages/erlang-base_1%253a23.1.5-1_amd64.deb':
      sha256: 943d8f7f299dd27a2b91993a26cc18988039d83c504934d18fe6dbde16f7bd6e
    'https://github.com/hitachienergy/alternative-repo/raw/240393a45307781721021e597966da2a8291432f/2.0.x/x86_64/debian/packages/erlang-crypto_1%253a23.1.5-1_amd64.deb':
      sha256: d00e867f3d4508d78fbffab226c8247af937a9ffde46c2e77257ce1f258144f9
    'https://github.com/hitachienergy/alternative-repo/raw/240393a45307781721021e597966da2a8291432f/2.0.x/x86_64/debian/packages/erlang-eldap_1%253a23.1.5-1_amd64.deb':
      sha256: 2b982eb5da6adbd450f2f1791349f983fd2fc47bcb3b1c8a1f80412001e3261f
    'https://github.com/hitachienergy/alternative-repo/raw/240393a45307781721021e597966da2a8291432f/2.0.x/x86_64/debian/packages/erlang-ftp_1%253a23.1.5-1_amd64.deb':
      sha256: 59653ae7cdc921ba66fd0cdbdda9730bccdab84f92b78bf2b6bafdfc580abada
    'https://github.com/hitachienergy/alternative-repo/raw/240393a45307781721021e597966da2a8291432f/2.0.x/x86_64/debian/packages/erlang-inets_1%253a23.1.5-1_amd64.deb':
      sha256: 7b54b1e86e7c20c0fde33a10d3fb448baba05bf5afc27c56ed8b9d7f31f934c7
    'https://github.com/hitachienergy/alternative-repo/raw/240393a45307781721021e597966da2a8291432f/2.0.x/x86_64/debian/packages/erlang-mnesia_1%253a23.1.5-1_amd64.deb':
      sha256: 4060bac983ca1975a6f8701e3bfcb9044a642dcd64a52f0e2873e5e758306924
    'https://github.com/hitachienergy/alternative-repo/raw/240393a45307781721021e597966da2a8291432f/2.0.x/x86_64/debian/packages/erlang-os-mon_1%253a23.1.5-1_amd64.deb':
      sha256: 9deee80e525470ddc1aeddd84e16726440dc9d66d174ce72535fcd56c39e10ab
    'https://github.com/hitachienergy/alternative-repo/raw/240393a45307781721021e597966da2a8291432f/2.0.x/x86_64/debian/packages/erlang-parsetools_1%253a23.1.5-1_amd64.deb':
      sha256: 4ccd3a68fa3e3511b23f86e139b27ba0d3c3fa6c99a6ae2f0bf4334d28a9f432
    'https://github.com/hitachienergy/alternative-repo/raw/240393a45307781721021e597966da2a8291432f/2.0.x/x86_64/debian/packages/erlang-public-key_1%253a23.1.5-1_amd64.deb':
      sha256: d2117428607738461cafc450c8711deb1d0afeb9c7144746007a032e66e98983
    'https://github.com/hitachienergy/alternative-repo/raw/240393a45307781721021e597966da2a8291432f/2.0.x/x86_64/debian/packages/erlang-runtime-tools_1%253a23.1.5-1_amd64.deb':
      sha256: cf86b47be619c29180349473956f248ba2827b5433316e6fca97d512cee40c27
    'https://github.com/hitachienergy/alternative-repo/raw/240393a45307781721021e597966da2a8291432f/2.0.x/x86_64/debian/packages/erlang-snmp_1%253a23.1.5-1_amd64.deb':
      sha256: f5f3165e2d2ac31b005fe3f422d59c09fb34a226679b5217f9c2e302d380106b
    'https://github.com/hitachienergy/alternative-repo/raw/240393a45307781721021e597966da2a8291432f/2.0.x/x86_64/debian/packages/erlang-ssl_1%253a23.1.5-1_amd64.deb':
      sha256: a15ffb59182926d0e84465a0bd18f133d45293abcc0f848fd52014d749c3defe
    'https://github.com/hitachienergy/alternative-repo/raw/240393a45307781721021e597966da2a8291432f/2.0.x/x86_64/debian/packages/erlang-syntax-tools_1%253a23.1.5-1_amd64.deb':
      sha256: eea9b02271461289ca339087f551dd326fa68dc67929998ac8370e7b44d4046f
    'https://github.com/hitachienergy/alternative-repo/raw/240393a45307781721021e597966da2a8291432f/2.0.x/x86_64/debian/packages/erlang-tftp_1%253a23.1.5-1_amd64.deb':
      sha256: 1c97ead185ffaf838bbcfd9a25f2a7c334496a63b4e597dbd682efad7537e457
    'https://github.com/hitachienergy/alternative-repo/raw/240393a45307781721021e597966da2a8291432f/2.0.x/x86_64/debian/packages/erlang-tools_1%253a23.1.5-1_amd64.deb':
      sha256: 96ba6054e5e7a64fe88c621f560270c8cc1967e8b10ff8a040e6460d37c215ae
    'https://github.com/hitachienergy/alternative-repo/raw/240393a45307781721021e597966da2a8291432f/2.0.x/x86_64/debian/packages//erlang-xmerl_1%253a23.1.5-1_amd64.deb':
      sha256: 393aab19e8e43b047230dcf8d83310e1da2bd45d9bb2646eb0b2eeb9b2b703cd
