---
- name: Reload sshd
  systemd:
    name: sshd
    state: reloaded

- name: Restart sshd
  systemd:
    name: sshd
    state: restarted

- name: Restart waagent
  systemd:
    name: waagent
    state: restarted
