#!/bin/bash
#
# Copyright 2019 ABB. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

NEW_IP=$2

echo "==== Obtaining new credentials for rejoining Kubernetes cluster ===="

kubeadm_token=$(kubeadm token create --ttl 4h --description "Token generated by Epiphany for 'kubeadm join'.")

cert_hash=$(openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //')

server_api_url="$NEW_IP:6443"

echo "Use following credentials for joining cluster. Execute following actions ONLY on worker Nodes."
echo "Modify file /etc/kubeadm/kubeadm-join.yml on each node with following values:"
echo "token: $kubeadm_token"
echo "cert hash: sha256:$cert_hash"
echo "server api url: $server_api_url"

echo "==== Obtaining credentials completed ===="
