---
kind: infrastructure/cloud-os-image-defaults
title: "Cloud OS Image Defaults"
name: default
specification:
  almalinux-8-x86_64:
    publisher: almalinux
    offer: almalinux-x86_64
    sku: 8-gen2
    version: '8.8.2023072701'  # offers with plan ids: 8_4 and 8_5-gen2 have been removed from the marketplace for new purchases
  rhel-8-x86_64:
    publisher: RedHat
    offer: rhel-raw
    sku: 8-raw-gen2
    version: '8.4.2022031606'
  ubuntu-20.04-x86_64:
    publisher: Canonical
    offer: 0001-com-ubuntu-server-focal
    sku: 20_04-lts-gen2
    version: "20.04.202504250"
  ubuntu-pro-20.04-x86_64:
    publisher: Canonical
    offer: 0001-com-ubuntu-pro-focal
    sku: pro-20_04-lts-gen2
    version: "20.04.202504240"
    plan:
      name: pro-20_04-lts-gen2
      publisher: canonical
      product: 0001-com-ubuntu-pro-focal
